# Generated by Django 5.0.3 on 2025-03-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_id', models.CharField(max_length=255)),
                ('anilist_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('alt_titles', models.JSONField(blank=True, default=list, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('alt_description', models.JSONField(blank=True, default=list, null=True)),
                ('original_language', models.CharField(blank=True, max_length=255, null=True)),
                ('last_chapter', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('latest_chapter', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True)),
                ('banner_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='manga.tag')),
            ],
        ),
    ]
