# Generated by Django 5.0.3 on 2025-03-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_dex_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('datasaver_images', models.JSONField(blank=True, default=list, null=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('hash_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.manga')),
            ],
            options={
                'ordering': ['chapter_number'],
            },
        ),
    ]
