# Generated by Django 5.0.3 on 2025-03-30 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_chapter', models.CharField(blank=True, max_length=255, null=True)),
                ('progress_percentage', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_interacted', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='manga.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_interacted'],
                'unique_together': {('user', 'manga')},
            },
        ),
    ]
