server:
  http_listen_port: 7201
  grpc_listen_port: 9095
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0

multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data/tsdb
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: mimir
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: mimir
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

store_gateway:
  sharding_ring:
    kvstore:
      store: memberlist
    replication_factor: 1

memberlist:
  join_members: ["mimir:7946"]