# Generated by Django 5.0.3 on 2025-05-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('banner', 'Banner'), ('icon', 'Icon'), ('logo', 'Logo'), ('background', 'Background'), ('thumbnail', 'Thumbnail'), ('other', 'Other')], max_length=20)),
                ('image', models.ImageField(upload_to='assets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
